#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in River

WALLPAPER='/home/username/Pictures/wallpapers/ign-0000.png'

swaybg --output '*' --mode fill --image "$WALLPAPER"
