# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/bird.png'

# Special
background='#5b402c'
foreground='#f1eae2'
cursor='#f1eae2'

# Colors
color0='#5b402c'
color1='#E1C7A6'
color2='#E2CAA9'
color3='#E5CEAE'
color4='#E5CEAE'
color5='#E5CEAE'
color6='#EDDBC7'
color7='#f1eae2'
color8='#a8a39e'
color9='#E1C7A6'
color10='#E2CAA9'
color11='#E5CEAE'
color12='#E5CEAE'
color13='#E5CEAE'
color14='#EDDBC7'
color15='#f1eae2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
