# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/ign_ferrari3.png'

# Special
background='#191c24'
foreground='#d5d8df'
cursor='#d5d8df'

# Colors
color0='#191c24'
color1='#7B8495'
color2='#848C9C'
color3='#8F98A7'
color4='#9CA4B2'
color5='#A4ACBA'
color6='#B0B7C4'
color7='#d5d8df'
color8='#95979c'
color9='#7B8495'
color10='#848C9C'
color11='#8F98A7'
color12='#9CA4B2'
color13='#A4ACBA'
color14='#B0B7C4'
color15='#d5d8df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
