# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/ign-0000.png'

# Special
background='#181b23'
foreground='#dddee0'
cursor='#dddee0'

# Colors
color0='#181b23'
color1='#847E81'
color2='#7B838B'
color3='#908F8F'
color4='#A09A9C'
color5='#ADAEB1'
color6='#B8BDC6'
color7='#dddee0'
color8='#9a9b9c'
color9='#847E81'
color10='#7B838B'
color11='#908F8F'
color12='#A09A9C'
color13='#ADAEB1'
color14='#B8BDC6'
color15='#dddee0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
