#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/username/Pictures/wallpapers/ign_ferrari3.png'

swaybg --output '*' --mode fill --image "$WALLPAPER"
