## Colors configuration
[colors.primary]
background = "#101b23"
foreground = "#e1bbaf"

[colors.normal]
black   = "#101b23"
red     = "#9D5760"
green   = "#AE5C65"
yellow  = "#9D6461"
blue    = "#BC6269"
magenta = "#C7656C"
cyan    = "#D06F6F"
white   = "#e1bbaf"

[colors.bright]
black   = "#9d827a"
red     = "#9D5760"
green   = "#AE5C65"
yellow  = "#9D6461"
blue    = "#BC6269"
magenta = "#C7656C"
cyan    = "#D06F6F"
white   = "#e1bbaf"
