## Colors configuration
[colors.primary]
background = "#181b23"
foreground = "#dddee0"

[colors.normal]
black   = "#181b23"
red     = "#847E81"
green   = "#7B838B"
yellow  = "#908F8F"
blue    = "#A09A9C"
magenta = "#ADAEB1"
cyan    = "#B8BDC6"
white   = "#dddee0"

[colors.bright]
black   = "#9a9b9c"
red     = "#847E81"
green   = "#7B838B"
yellow  = "#908F8F"
blue    = "#A09A9C"
magenta = "#ADAEB1"
cyan    = "#B8BDC6"
white   = "#dddee0"
