# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/nord_naruto_2.png'

# Special
background='#101b23'
foreground='#e1bbaf'
cursor='#e1bbaf'

# Colors
color0='#101b23'
color1='#9D5760'
color2='#AE5C65'
color3='#9D6461'
color4='#BC6269'
color5='#C7656C'
color6='#D06F6F'
color7='#e1bbaf'
color8='#9d827a'
color9='#9D5760'
color10='#AE5C65'
color11='#9D6461'
color12='#BC6269'
color13='#C7656C'
color14='#D06F6F'
color15='#e1bbaf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
