# Shell variables
# Generated by 'wal'
wallpaper='/home/username/Pictures/wallpapers/manhattan.jpg'

# Special
background='#12171b'
foreground='#b8a5a8'
cursor='#b8a5a8'

# Colors
color0='#12171b'
color1='#704955'
color2='#7E615E'
color3='#795964'
color4='#7F6567'
color5='#825058'
color6='#80615F'
color7='#b8a5a8'
color8='#807375'
color9='#704955'
color10='#7E615E'
color11='#795964'
color12='#7F6567'
color13='#825058'
color14='#80615F'
color15='#b8a5a8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
