#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Wayfire

WALLPAPER='/home/username/Pictures/wallpapers/nord_naruto_2.png'

swaybg --output '*' --mode fill --image "$WALLPAPER"
