#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/river"
RASI="$DIR/rofi/bindings.rasi"

# Run
rofi -show calc \
     -theme ${RASI}

					    					    


